version: 2
jobs:
    build:
        docker:
            - image: circleci/openjdk:11-jdk
              environment:
                  discovery.type: single-node
        branches:
            only:
                - publishing
        steps:
            - checkout
            - run: sudo apt-get install openjdk-11-jdk-headless openjdk-8-jdk-headless
            - restore_cache:
                key: jeromq-{{ checksum "pom.xml" }}
            - run: mvn dependency:go-offline dependency:resolve-plugins
            - run:
                command: mvn compile -Djdk.compile.home=/usr/lib/jvm/java-8-openjdk-amd64
                environment:
                    JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
            - run:
                command: mvn site deploy -Dmaven.test.skip=true -Dmaven.main.skip=true -s .circleci/settings.xml -Djdk.compile.home=/usr/lib/jvm/java-8-openjdk-amd64
                environment:
                    JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
            - save_cache:
                paths:
                    - ~/.m2
                key: jeromq-{{ checksum "pom.xml" }}
            - store_test_results:
                path: target/surefire-reports
