version: 2.1
jobs:
    checkout:
        docker:
            - image: circleci/openjdk:17-jdk-buster
        steps:
            - checkout
            - restore_cache:
                key: jeromq-{{ checksum "pom.xml" }}
            - restore_cache:
                key: jeromq-mavendep
            - run: mkdir -p /home/circleci/.sonar/cache /home/circleci/.m2/repository
            - run:
                command: "mvn -B dependency:resolve dependency:resolve-plugins -s .circleci/settings.xml -Pandroid,sonar,coverage,checkstyle"
                environment:
                    JAVA_HOME: /usr/local/openjdk-17
                    MAVEN_OPTS: "-Xmx1024m"
            - persist_to_workspace:
                root: /
                paths:
                    - home/circleci/.m2/repository
                    - home/circleci/.sonar/cache
                    - home/circleci/project
    jdk8:
        docker:
            - image: circleci/openjdk:8-buster
        steps:
            - persist_to_workspace:
                root: /usr/local
                paths:
                    - openjdk-8
    build:
        docker:
            - image: circleci/openjdk:17-jdk-buster
        steps:
            - attach_workspace:
                at: /tmp/ws
            - run:
                command: |
                    mv -n /tmp/ws/home/circleci/.m2 /home/circleci/
                    mv -n /tmp/ws/home/circleci/project/* /home/circleci/project/
                    mv -n /tmp/ws/home/circleci/project/.??* /home/circleci/project/
            - run:
                command: mvn -B clean compile site -Pcheckstyle -Djdk.compile.home=/tmp/ws/openjdk-8 -s .circleci/settings.xml
                environment:
                    JAVA_HOME: /usr/local/openjdk-17
                    MAVEN_OPTS: "-Xmx2048m"
            - persist_to_workspace:
                root: /
                paths:
                    - home/circleci/.m2/repository
                    - home/circleci/project/target
    testsj17:
        docker:
            - image: circleci/openjdk:17-jdk-buster
        steps:
            - attach_workspace:
                at: /tmp/ws
            - run:
                command: |
                    mv -n /tmp/ws/home/circleci/.m2 /home/circleci/
                    mv -n /tmp/ws/home/circleci/project/* /home/circleci/project/
                    mv -n /tmp/ws/home/circleci/project/.??* /home/circleci/project/
            - run:
                command: |
                    # If no symbolic name, it's a PR, will run sonar
                    if [ -n "$(git symbolic-ref HEAD 2>/dev/null )" ] ; then
                        SONAR="jacoco:report sonar:sonar -Psonar,coverage"
                        echo "Doing sonar"
                    else
                        SONAR=""
                    fi
                    mvn -B test $SONAR -Pskip -Darg.line="-Xmx2048m" -s .circleci/settings.xml
                environment:
                    JAVA_HOME: /usr/local/openjdk-17
                    MAVEN_OPTS: "-Xmx1024m"
            - store_test_results:
                path: target/surefire-reports
            - persist_to_workspace:
                root: /
                paths:
                    - home/circleci/.m2/repository
                    - home/circleci/.sonar/cache
    testsj11:
        docker:
            - image: circleci/openjdk:11-buster
        steps:
            - attach_workspace:
                at: /tmp/ws
            - run:
                command: |
                    mv -n /tmp/ws/home/circleci/.m2 /home/circleci/
                    mv -n /tmp/ws/home/circleci/.sonar /home/circleci/
                    mv -n /tmp/ws/home/circleci/project/* /home/circleci/project/
                    mv -n /tmp/ws/home/circleci/project/.??* /home/circleci/project/
            - run:
                command: |
                    mvn -B test -Pskip -Darg.line="-Xmx2048m" -s .circleci/settings.xml
                environment:
                    JAVA_HOME: /usr/local/openjdk-11
                    MAVEN_OPTS: "-Xmx512m"
            - store_test_results:
                path: target/surefire-reports
            #don't persist_to_workspace, can't be done in parallel with testsj13
    testsj8:
        docker:
            - image: circleci/openjdk:8-buster
        steps:
            - attach_workspace:
                at: /tmp/ws
            - run:
                command: |
                    mv -n /tmp/ws/home/circleci/.m2 /home/circleci/
                    mv -n /tmp/ws/home/circleci/.sonar /home/circleci/
                    mv -n /tmp/ws/home/circleci/project/* /home/circleci/project/
                    mv -n /tmp/ws/home/circleci/project/.??* /home/circleci/project/
            - run:
                command: |
                    mvn -B test -Pskip -Darg.line="-Xmx2048m" -s .circleci/settings.xml
                environment:
                    JAVA_HOME: /usr/local/openjdk-8
                    MAVEN_OPTS: "-Xmx512m"
            - store_test_results:
                path: target/surefire-reports
            #don't persist_to_workspace, can't be done in parallel with testsj13
    testsandroid:
        docker:
            - image: circleci/openjdk:17-jdk-buster
        steps:
            - attach_workspace:
                at: /tmp/ws
            - run:
                command: |
                    mv -n /tmp/ws/home/circleci/.m2 /home/circleci/
                    mv -n /tmp/ws/home/circleci/.sonar /home/circleci/
                    mv -n /tmp/ws/home/circleci/project/* /home/circleci/project/
                    mv -n /tmp/ws/home/circleci/project/.??* /home/circleci/project/
            - run:
                command: |
                    mvn -B test -Pskip,android -Darg.line="-Xmx2048m" -s .circleci/settings.xml -Dmaven.test.skip=true
                environment:
                    JAVA_HOME: /usr/local/openjdk-17
                    MAVEN_OPTS: "-Xmx2048m"
    publish:
        docker:
            - image: circleci/openjdk:17-jdk-buster
        steps:
            - attach_workspace:
                at: /tmp/ws
            - run:
                command: |
                    mv -n /tmp/ws/home/circleci/.m2 /home/circleci/
                    mv -n /tmp/ws/home/circleci/.sonar /home/circleci/
                    mv -n /tmp/ws/home/circleci/project/* /home/circleci/project/
                    mv -n /tmp/ws/home/circleci/project/.??* /home/circleci/project/
            - run:
                command: |
                    if [ -n "$SECRING_GPG_ASC_BASE64" ] ; then
                        echo "$SECRING_GPG_ASC_BASE64" | base64 --decode | gpg --batch --no-tty --import --yes
                        GPGSIGN="-P gpgsign"
                    fi
                    # If no symbolic name, it's a PR, will not publish results
                    # If not the official github, it's a fork, don't publish either
                    if [ -n "$(git symbolic-ref HEAD 2>/dev/null )"  -a "$CIRCLE_REPOSITORY_URL" == "git@github.com:zeromq/jeromq.git" ] ; then
                        PUBLISH="deploy"
                    else
                        PUBLISH="install"
                    fi
                    echo "publishing jobs: $PUBLISH"
                    mvn -B $PUBLISH -Pskip $GPGSIGN -Dmaven.test.skip=true -Dmaven.javadoc.skip=false -s .circleci/settings.xml
                environment:
                    JAVA_HOME: /usr/local/openjdk-17
                    MAVEN_OPTS: "-Xmx2048m"
            - store_artifacts:
                path: /home/circleci/.m2/repository/org/zeromq/jeromq
                destination: /
            - persist_to_workspace:
                root: /
                paths:
                    - home/circleci/.m2/repository
                    - home/circleci/.sonar/cache
    savecache:
        docker:
            - image: circleci/openjdk:17-jdk-buster
        steps:
            - attach_workspace:
                at: /tmp/ws
            - run:
                command: |
                    mv /tmp/ws/home/circleci/project/pom.xml /home/circleci/project/
                    mv /tmp/ws/home/circleci/.m2 /home/circleci/
                    mv /tmp/ws/home/circleci/.sonar /home/circleci/
            - save_cache:
                paths:
                    - /home/circleci/.sonar/cache
                key: jeromq-{{ checksum "pom.xml" }}
            - save_cache:
                paths:
                    - /home/circleci/.m2/repository
                key: jeromq-mavendep
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - checkout
      - jdk8
      - build:
          requires:
              - checkout
              - jdk8
      - testsj8:
          requires:
              - build
      - testsj11:
          requires:
              - build
      - testsj17:
          requires:
              - build
      - testsandroid:
          requires:
              - build
      - publish:
          requires:
              - testsj8
              - testsj11
              - testsj17
      - savecache:
          requires:
              - publish
