<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>fr.loghub</groupId>
        <artifactId>jeromq-pom</artifactId>
        <version>2.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>jeromq-zactor</artifactId>

    <name>JeroMQ :: ZActor</name>
    <description>ZActor implementation for jeromq</description>

    <dependencies>
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>jeromq-core</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>biz.aQute.bnd</groupId>
                <artifactId>bnd-maven-plugin</artifactId>
                <extensions>true</extensions>
                <executions>
                    <execution>
                        <id>default-jar</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                        <configuration>
                            <bnd>
                Bundle-SymbolicName: $[project.groupId].$[project.artifactId]
                Export-Package: org.zeromq.*
                -jpms-module-info: $[Bundle-SymbolicName];access=0
                            </bnd>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
